#!/bin/bash

# Arch Linux Install Script 
# -------------------------
# author    : prstephens
#             https://github.com/prstephens           
# project   : https://github.com/prstephens/archinstallscript
# license   : LGPL-3.0 (http://opensource.org/licenses/lgpl-3.0.html)
# referance : https://wiki.archlinux.org/index.php/Installation_guide

# Globals
BACKTITLE="Arch Installer v3"
MIRRORLIST_URL="https://archlinux.org/mirrorlist/?country=GB&protocol=https&use_mirror_status=on"
BASE_URL="https://raw.githubusercontent.com/prstephens/archinstallscript/master/"

# --------------------------------------------------------

mainmenu(){
        if [ "${1}" = "" ]; then
                nextitem="."
        else
                nextitem=${1}
        fi
        options=()
        options+=("1)" "Partition disk (cfdisk)")
        options+=("2)" "Select partitions to mount")
        options+=("3)" "Setup user and root password")
        options+=("4)" "Install")
        options+=("" "")
        options+=("5)" "Finish and reboot")

        sel=$(whiptail --backtitle "${BACKTITLE}" --title "Main Menu" --menu "" --cancel-button "Exit" --default-item "${nextitem}" 20 78 0\
                "${options[@]}" \
                3>&1 1>&2 2>&3)
        if [ "$?" = "0" ]; then
                case ${sel} in
                        "1)")
                                diskpartcfdisk
                                nextitem="2)"
                        ;;
                        "2)")
                                choosepartitions
                                nextitem="3)"
                        ;;
                        "3)")
                                getuserinfo
                                nextitem="4)"
                        ;;
                        "4)")
                                performinstall
                                configuration
                                installbootloader
                                setupuser
                                finish
                                nextitem="5)"
                        ;;
                        "5)")
                                rebootpc
                                nextitem="5)"
                        ;;
                esac
                mainmenu "${nextitem}"
        else
                clear
        fi
}

diskpartcfdisk(){
	device=$( selectdisk "Edit Partitions (cfdisk)" )
        if [ "$?" = "0" ]; then
            clear
            cfdisk ${device}
        fi
}

selectdisk(){
        items=$(lsblk -d -p -n -l -o NAME,SIZE -e 7,11)
        options=()
        IFS_ORIG=$IFS
        IFS=$'\n'
        for item in ${items}
        do  
                options+=("${item}" "")
        done
        IFS=$IFS_ORIG
        result=$(whiptail --backtitle "${BACKTITLE}" --title "${1}" --menu "" 0 78 0 "${options[@]}" 3>&1 1>&2 2>&3)
        if [ "$?" != "0" ]
        then
                return 1
        fi
        echo ${result%%\ *}
        return 0    
}

choosepartitions(){
	itemsinfo=$(lsblk -o NAME,SIZE,FSTYPE)
        items=$(lsblk -p -n -l -o NAME -e 7,11)
        deviceitems=$(lsblk -d -n -l -o NAME -e 7,11)
        options=()
        optionstoremove=()
        IFS_ORIG=$IFS
        IFS=$'\n'
        for item in ${deviceitems}
        do  
                optionstoremove+=("/dev/${item}")
        done
        for item in ${items}
        do  
                if [[ ! " ${optionstoremove[@]} " =~ " ${item} " ]]; then
                        options+=("${item}" "")
                fi
        done
	bootdev=$(whiptail --backtitle "${BACKTITLE}" --title "Select Boot partition" --menu "${itemsinfo}" --default-item "${bootdev}" 0 78 0 \
		"none" "-" \
		"${options[@]}" \
		3>&1 1>&2 2>&3)
	if [ ! "$?" = "0" ]; then
		return 1
	else
		if [ "${bootdev}" = "none" ]; then
			bootdev=
		fi
	fi
	swapdev=$(whiptail --backtitle "${BACKTITLE}" --title "Select Swap partition" --menu "${itemsinfo}" --default-item "${swapdev}" 0 78 0 \
		"none" "-" \
		"${options[@]}" \
		3>&1 1>&2 2>&3)
	if [ ! "$?" = "0" ]; then
		return 1
	else
		if [ "${swapdev}" = "none" ]; then
			swapdev=
		fi
	fi
	rootdev=$(whiptail --backtitle "${BACKTITLE}" --title "Select Root partition" --menu "${itemsinfo}" --default-item "${rootdev}" 0 78 0 \
		"${options[@]}" \
		3>&1 1>&2 2>&3)
	if [ ! "$?" = "0" ]; then
		return 1
	fi
	realrootdev=${rootdev}
	
        msg=""
	msg=${msg}"Boot     : "${bootdev}"\n"
	msg=${msg}"Swap     : "${swapdev}"\n"
	msg=${msg}"Root     : "${rootdev}"\n\n"
	if (whiptail --backtitle "${BACKTITLE}" --title "Are these values correct?" --yesno "${msg}" 0 78) then
		mainmenu "3)"
        else
                choosepartitions
        fi
}

getuserinfo(){
        hostname=$(whiptail --backtitle "$BACKTITLE" --inputbox "Enter hostname:" 8 78 3>&1 1>&2 2>&3)
        user=$(whiptail --backtitle "$BACKTITLE" --inputbox "Enter admin username:" 8 78 3>&1 1>&2 2>&3)

        password="x"
        password2="xx"
        passphrase_invalid_message=""

        while [[ "$password" != "$password2" ]]; do

            password=$(whiptail --backtitle "$BACKTITLE" --passwordbox "${passphrase_invalid_message}Please enter the admin password:" 8 78 3>&1 1>&2 2>&3)
            password2=$(whiptail --backtitle "$BACKTITLE" --passwordbox "Please repeat the admin password:" 8 78 3>&1 1>&2 2>&3)
            passphrase_invalid_message="Passwords do not match! "

        done

        msg=${msg}"Hostname : "${hostname}"\n"
        msg=${msg}"User     : "${user}"\n\n"
}

performinstall(){
        whiptail --backtitle "${BACKTITLE}" --title "Are these values correct?" --yesno "${msg}" 0 78 3>&1 1>&2 2>&3
        if ([ ! "$?" = "0" ];) then
		mainmenu "1)"
	fi

        if (whiptail --backtitle "${BACKTITLE}" --title "### WARNING ###" --yesno "Do you want to format ${bootdev}? \n\nTHIS COULD ERASE EXISITING OPERATING SYSTEM BOOTLOADERS" --defaultno 0 78) then
		mkfs.fat -F 32 ${bootdev}
        else
                mainmenu "1)"
	fi
        
        clear

        timedatectl set-ntp true

        # Setup the partitions
        echo "### STARTING INSTALL ###"
        read -p "You are about to wipe ${rootdev}? [y/N]: " wipe
        if [ $wipe = 'y' ]
        then
                mkfs.btrfs $rootdev
        else
                echo "Install stopped"
                exit
        fi

        if [ ! "${swapdev}" = "" ]
        then
                mkswap $swapdev
                swapon $swapdev
        fi

        #root
        mount $rootdev /mnt

        #BTRFS subvolumes
        btrfs su cr /mnt/@
        btrfs su cr /mnt/@home
        btrfs su cr /mnt/@var_log
        btrfs su cr /mnt/@snapshots
        umount /mnt

        mount -o noatime,commit=120,compress=zstd,space_cache=v2,subvol=@ $rootdev /mnt
        
        # You need to manually create folders to mount the other subvolumes at
        mkdir -p /mnt/{boot,home,var/log,.snapshots}

        mount -o noatime,commit=120,compress=zstd,space_cache=v2,subvol=@home $rootdev /mnt/home

        mount -o noatime,commit=120,compress=zstd,space_cache=v2,subvol=@var_log $rootdev /mnt/var/log

        mount -o noatime,commit=120,compress=zstd,space_cache=v2,subvol=@snapshots $rootdev /mnt/.snapshots

        mount $bootdev /mnt/boot

        echo "Starting install.."
        
        pacstrap /mnt $(< /tmp/packages)

        # Generate fstab
        genfstab -U /mnt >> /mnt/etc/fstab
}

installbootloader(){
        clear
        arch-chroot /mnt grub-install --target=x86_64-efi --efi-directory=/boot --bootloader-id=GRUB
        arch-chroot /mnt sed -i 's/^GRUB_GFXMODE=.*$/GRUB_GFXMODE=1920x1080x32/' /etc/default/grub
        arch-chroot /mnt sed -i 's/^GRUB_CMDLINE_LINUX_DEFAULT=.*$/GRUB_CMDLINE_LINUX_DEFAULT="quiet loglevel=3 rd.systemd.show_status=false nowatchdog mitigations=off"/' /etc/default/grub
        arch-chroot /mnt grub-mkconfig -o /boot/grub/grub.cfg
}

configuration(){
        clear

        # Set Cloudfare as our DNS
        cat <<EOT > /mnt/etc/resolv.conf
options timeout:1
options single-request

nameserver 1.1.1.1
nameserver 1.0.0.1
nameserver 8.8.8.8
EOT

        chattr +i /mnt/etc/resolv.conf

        cat <<EOT >> /mnt/etc/NetworkManager/NetworkManager.conf
[main]
dns=none
systemd-resolved=false
EOT

        cat <<EOT >> /mnt/etc/hosts
192.168.1.192   rainbowdash.localdomain rainbowdash
192.168.1.66    libreelec.localdomain libreelec
EOT

        echo "Updating pacman mirrors to awesomeness..."
        # Update pacman mirror list
        arch-chroot /mnt reflector --verbose -c GB -l 25 --age 12 -p http -p https --sort rate --save /etc/pacman.d/mirrorlist

        echo "Setting up spacetime continuum..."
        # Set date time
        arch-chroot /mnt ln -sf /usr/share/zoneinfo/Europe/London /etc/localtime
        arch-chroot /mnt hwclock --systohc

        # Set locale to en_US.UTF-8 UTF-8
        arch-chroot /mnt sed -i '/en_GB.UTF-8 UTF-8/s/^#//g' /etc/locale.gen
        arch-chroot /mnt locale-gen
        echo "LANG=en_GB.UTF-8" >> /mnt/etc/locale.conf

        # Set the console keymap
        echo "KEYMAP=uk" >> /mnt/etc/vconsole.conf

        # Set hostname
        echo "${hostname}" > /mnt/etc/hostname
        echo "127.0.1.1 ${hostname}.localdomain  ${hostname}" >> /mnt/etc/hosts

        # Set keyboard FN keys to act normal!
        echo "options hid_apple fnmode=2" > /mnt/etc/modprobe.d/hid_apple.conf
        
        # nano syntax highlighting
        echo "include /usr/share/nano/*.nanorc" >> /mnt/etc/nanorc

        # swappiness config for swap
        echo "vm.swappiness=10" >> /mnt/etc/sysctl.d/99-swappiness.conf

        # PulseAudio
        arch-chroot /mnt sed -i '/load-module module-suspend-on-idle/ s/^#*/#/' /etc/pulse/default.pa

        # add btrfs to modules
        sed -i 's/^MODULES=.*$/MODULES=(i915 btrfs)/' /mnt/etc/mkinitcpio.conf
        arch-chroot /mnt mkinitcpio -P

        # Intel X11 config
        cat <<EOT > /mnt/etc/X11/xorg.conf.d/20-intel.conf 
Section "Device"
  Identifier "Intel Graphics"
  Driver "intel"
EndSection
EOT

        # Create the pacman mirrorlist updater service
        cat <<EOT > /mnt/etc/systemd/system/reflector.service
[Unit]
Description=Pacman mirrorlist update
Wants=network-online.target
After=network-online.target nss-lookup.target
[Service]
Type=oneshot
ExecStart=/usr/bin/reflector -c GB -l 25 --age 12 -p http -p https --sort rate --save /etc/pacman.d/mirrorlist
[Install]
WantedBy=multi-user.target
EOT

        cat <<EOT > /mnt/etc/modprobe.d/blacklist.conf
blacklist iTCO_wdt
blacklist pcspkr
blacklist joydev
blacklist mousedev
blacklist mac_hid
blacklist uvcvideo
blacklist xpad
EOT
        # for 11th cpu or lower
        cat <<EOT > /mnt/etc/modprobe.d/i915.conf
options i915 enable_guc=2
EOT

        # Enable services
        echo "Enabling services..."
        arch-chroot /mnt systemctl enable NetworkManager.service
        arch-chroot /mnt systemctl enable bluetooth.service
        arch-chroot /mnt systemctl enable cups.service
        arch-chroot /mnt systemctl enable reflector
        arch-chroot /mnt systemctl enable reflector.timer
        arch-chroot /mnt systemctl enable fstrim.timer
        arch-chroot /mnt systemctl enable sshd

        arch-chroot /mnt systemctl mask lvm2-monitor
        arch-chroot /mnt systemctl mask systemd-random-seed
}

setupuser(){
        arch-chroot /mnt useradd -m -G wheel $user
        arch-chroot /mnt sed -i 's/# %wheel ALL=(ALL) ALL/%wheel ALL=(ALL) ALL/' /etc/sudoers
        echo "Defaults insults" >> /mnt/etc/sudoers
        echo "${user} ALL=(ALL) NOPASSWD: /usr/bin/mount" >> /mnt/etc/sudoers
        echo "${user} ALL=(ALL) NOPASSWD: /usr/bin/umount" >> /mnt/etc/sudoers
        echo "${user} ALL=(ALL) NOPASSWD: /usr/bin/sed" >> /mnt/etc/sudoers

        # Set root password
        echo "Setting user and root password..."
        echo "${user}:${password}" | arch-chroot /mnt chpasswd
        echo "root:${password}" | arch-chroot /mnt chpasswd

        # config files
        echo "Getting some sweet config files..."
        arch-chroot /mnt curl -sL $BASE_URL/sweet/.Xresources -o /home/$user/.Xresources
        arch-chroot /mnt curl -sL $BASE_URL/sweet/.bashrc -o /home/$user/.bashrc
        arch-chroot /mnt chown $user:$user /home/$user/.Xresources
        arch-chroot /mnt chown $user:$user /home/$user/.bashrc
        arch-chroot /mnt curl -sL $BASE_URL/sweet/issue -o /etc/issue

        # set custom pacman.conf 
        arch-chroot /mnt mv /etc/pacman.conf /etc/pacman.conf.bak
        arch-chroot /mnt curl -sL $BASE_URL/sweet/pacman.conf -o /etc/pacman.conf
        
        # Copy post-install file to /home/$user
        echo "Copy post-install file to /home/${user}..."
        arch-chroot /mnt curl -sL $BASE_URL/post-install -o /home/$user/post-install
        arch-chroot /mnt chown $user:$user /home/$user/post-install
        arch-chroot /mnt chmod a+x /home/$user/post-install

        # Add shell-option to ~/.inputrc to enable case-insensitive tab completion
        if [ ! -a /mnt/home/$user/.inputrc ]; then echo '$include /etc/inputrc' > /mnt/home/$user/.inputrc; fi
        echo 'set completion-ignore-case On' >> /mnt/home/$user/.inputrc
        arch-chroot /mnt chown $user:$user /home/$user/.inputrc

        # Create user xinit config file 
        echo "Creating .xinitrc file..."
        head -n -5 /mnt/etc/X11/xinit/xinitrc >> /mnt/home/$user/.xinitrc
        arch-chroot /mnt chown $user:$user /home/$user/.xinitrc    

        # BBC Micro console font :)
        arch-chroot /mnt curl -sL $BASE_URL/fonts/acorn/console/bedstead-10.psf.gz -o /usr/share/kbd/consolefonts/bedstead-10.psf.gz
        arch-chroot /mnt curl -sL $BASE_URL/fonts/acorn/console/bedstead-20.psf.gz -o /usr/share/kbd/consolefonts/bedstead-20.psf.gz
        arch-chroot /mnt curl -sL $BASE_URL/fonts/acorn/console/acorn.psf.gz -o /usr/share/kbd/consolefonts/acorn.psf.gz
        arch-chroot /mnt chmod 644 /usr/share/kbd/consolefonts/bedstead-*.*
        arch-chroot /mnt chmod 644 /usr/share/kbd/consolefonts/acorn.psf.gz
        echo "FONT=bedstead-10" >> /mnt/etc/vconsole.conf
}

rebootpc(){
        if (whiptail --backtitle "${BACKTITLE}" --yesno "Reboot?" --defaultno 8 78) then
                clear
                umount -a
                reboot
        fi
}

finish(){
        whiptail --backtitle "$BACKTITLE" --msgbox --title "Congratulations" "Install Complete\n\nReturn to main menu and select 'Finsh and Reboot'" 0 78
        nextitem="5)"
}

# --------------------------------------------------------

checkconnection(){
        if [[ $(ping -q -w1 -c1 google.com &>/dev/null && echo online || echo offline) == "offline" ]]; 
            then
                whiptail --backtitle "$BACKTITLE" --msgbox --title "No Network Connection" "You need to be connected to the Internet.\n\nInstallation stopped." 0 78
                exit
        fi
}

updatemirrors(){
        curl -sL "$MIRRORLIST_URL" | sed -e 's/^#Server/Server/' -e '/^#/d' | rankmirrors -n 5 - > /etc/pacman.d/mirrorlist
}

dependencies(){
        pacman -Sy --noconfirm pacman-contrib
}

getpackagelist(){
        curl -sL $BASE_URL/packages -o /tmp/packages
}

initialise(){
        checkconnection
        dependencies
        updatemirrors
        getpackagelist
}

# --------------------------------------------------------

[[ ! -f /tmp/packages ]] && initialise

mainmenu