#!/bin/bash

if [ "$1" == "r" ]
then
	echo "resetting to linux..."
	sudo sed -i 's/^GRUB_DEFAULT=.*$/GRUB_DEFAULT="1>2"/' /etc/default/grub
	exit 0
fi

sudo sed -i 's/^GRUB_DEFAULT=.*$/GRUB_DEFAULT="3"/' /etc/default/grub
ans=$(zenity --question --text="Do you want to reboot to Windowz?")
rc=$?
if [[ rc -eq 0 ]]
then
    reboot
fi